# Dependencies
markdown:         redcarpet
highligher:       pygments

# Permalinks
permalink:        pretty

# Setup
title:            Imran Shakir
tagline:          Miscellaneous Ramblings
description:      Miscellaneous Ramblings

url:              http://ishakir.github.io
shorturl:         ishakir.github.io
baseurl:          /

paginate:         5

author:
  name:           Imran Shakir

version:          0.0.1

github:
  repo:           http://github.com/ishakir/ishakir.github.io

pages_list:
  About: '/about'
  Archive: '/archive'